import { Box } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import { defaultTheme } from '~/styles/theme'

const Home: NextPage = () => {
  const theme = defaultTheme
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box component='div' sx={{ color: theme.palette.primary.main }}>
        hello mui
      </Box>
    </div>
  )
}

export default Home
