import { Box, Button, Container, Paper, TextField, Typography } from '@mui/material'
import type { NextPage } from 'next'
import Head from 'next/head'
import { defaultTheme } from '~/styles/theme'
import 'regenerator-runtime'

import SpeechRecognition, { useSpeechRecognition } from 'react-speech-recognition'
import { useEffect } from 'react'

const Home: NextPage = () => {
  const theme = defaultTheme
  const { transcript, resetTranscript } = useSpeechRecognition()

  const startSpeechRecognition = () => {
    SpeechRecognition.startListening({
      continuous: true,
      // https://github.com/JamesBrill/react-speech-recognition/blob/master/docs/API.md
      language: 'ja',
    })
  }

  useEffect(() => {
    console.log(transcript)
  }, [transcript])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Box component='div'>
        <Container maxWidth='sm' sx={{ mt: theme.spacing(20) }}>
          <Box sx={{ borderRadius: theme.spacing(1), border: '2px solid' }}>
            <Box
              sx={{
                backgroundColor: theme.palette.primary.main,
              }}
            >
              <Box sx={{ paddingX: theme.spacing(1), color: theme.palette.text.secondary }}>Menu</Box>
            </Box>
            <Paper sx={{ padding: theme.spacing(4) }}>
              テキストを入力
              <TextField multiline fullWidth rows={20} sx={{ backgroundColor: theme.palette.background.paper }} />
              <Typography>トランスパイル{transcript}</Typography>
            </Paper>
          </Box>
          <Button onClick={startSpeechRecognition}>音声認識スタート</Button>
          <Button onClick={SpeechRecognition.stopListening}>音声認識ストップ</Button>
          <Button onClick={resetTranscript}>文章リセット</Button>
        </Container>
      </Box>
    </div>
  )
}

export default Home
